### ISSUE TITLE
Migrate to the Pelican's new plugin architecture

### ISSUE THREAD

**Issue by abdullahkhalids** [martenlienen/pelican-katex#10]
The Pelican project has a more structured approach to plugins now. Please see [the documentation note](https://docs.getpelican.com/en/latest/plugins.html#where-to-find-plugins).

Will it be possible to migrate pelican-katex over, so it is available to use with Pelican in the future as well?

Thanks.

**Comment by martenlienen** [comment]
That is certainly possible, however I am currently quite busy and since the old structure is still supported, it does not have high priority for me. If you want to send a PR that does the necessary restructuring, I would be happy to accept it.
