### ISSUE TITLE
Math rendering in Atom/RSS feeds

### ISSUE THREAD

**Issue by stephane-caron** [martenlienen/pelican-katex#11]
* Pelican: 4.8.0
* pelican-katex version: f9d6fe3b7be6eb898e13de86165bfd44d9414be4

Math formulas appear twice in Atom/RSS feeds.

## Example

For instance, [this page](https://scaron.info/robot-locomotion/contact-flexibility-and-force-control.html#flexibility-model) looks like this when rendered for the Web:

<img src="https://user-images.githubusercontent.com/1189580/209156942-e98c36a1-9e62-4c3a-9588-cfb351f0263c.png" width=500>

But in the Atom feed rendered in Thunderbird for the same paragraph appears as:

<img src="https://user-images.githubusercontent.com/1189580/209157195-638d2759-0b8a-4253-a7d0-9ed5d478735b.png" width=500>

## Probable cause

Diving a bit, I think the issue stems from neither CSS nor the KaTeX javascript being part of the ``<html>...`` headers in the feed. KaTeX renders MathML then HTML, and in the web version it is the HTML that is displayed and styled properly, while in the feed it is the MathML that renders properly (and then the HTML follows as redundant text).

Has someone already faced this issue and found a proper solution?

## Ways forward

I see at least two options that could fix this:

* Finding a way for the plugin not to generate the HTML for Atom/RSS feeds, leaving only the MathML (which is rendered OK most of the time).
* Injecting KaTeX into the feed's headers so that *e.g.* Thunderbird here would render it properly. (Not sure if Thunderbird allows Javascript in feeds though, to be checked.)

Other suggestions?

**Comment by martenlienen** [comment]
Thanks for reporting that. I am not using the RSS feeds feature, so I have not encountered that behavior before. A quick fix would be to configure
```python
KATEX = { "output": "mathml" }
```
though you will also only get mathml output on the web. If there is a way to know which format is generated at the moment in pelican, you could also do something like
```python
KATEX = { "output": "mathml" if format == "rss" else "htmlAndMathml" }
```
or we could build it directly into pelican-katex.

**Comment by martenlienen** [comment]
Also, you would only need to inject the katex stylesheets into the feed. After all, the point of pelican-katex is that you don't need the javascript anymore after rendering the math once.

**Comment by martenlienen** [comment]
I will close the issue for the time being. If you still have problems or find a nice solution, please feel free to reopen it.
