### ISSUE TITLE
No obvious way to change or escape rendering delimiters

### ISSUE THREAD

**Issue by andrew-vant** [martenlienen/pelican-katex#13]
pelican-katex looks for a dollar sign after whitespace as an inline-math delimiter, but that catches a fair number of dollar literals for me; e.g. when representing USD ($5000.00), or assembly-style hexadecimal ($AF34).

I would like to either disable katex rendering for certain pages, or escape the delimiter as-needed. I suggest some combination of the following:

* Allow escaping the delimiter with \.
* Allow changing or disabling the inline-math delimiter in pelicanconf.
* Allow toggling katex rendering via a page metadata variable.

(it's possible a method already exists, but I looked and couldn't find one)

**Comment by martenlienen** [comment]
I never thought about that because I did not need it until now. There is now a version 1.8.0 on PyPI that allows escaping `$` and `$$` with `\$` and `\$$`. Or rather that always worked but now there is a second pass that cleans up the backslash, so that it does not show up in the HTML output.

**Comment by andrew-vant** [comment]
Wow, that was fast. I just upgraded, and at first glance it seems to work.

A per-page or per-mode settings toggle would still be nice, simply because I use hex numbers a lot more often than complex math and it's a lot of escaping. But it's doable now and wasn't before, so thanks.
